### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by dagobertdu94** [Samuel-Harbord/SpectriteMod#33]
`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/29/19 6:40 PM
Description: Ticking entity

java.lang.ClassCastException: weather2.entity.EntityMovingBlock cannot be cast to net.minecraft.entity.EntityLivingBase
	at com.samuel.spectrite.eventhandlers.SpectriteGeneralEventHandler.onApplyLootingLevel(SpectriteGeneralEventHandler.java:749)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_SpectriteGeneralEventHandler_onApplyLootingLevel_LootingLevelEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:627)
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:619)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1180)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at weather2.entity.EntityMovingBlock.func_70071_h_(EntityMovingBlock.java:253)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.samuel.spectrite.eventhandlers.SpectriteGeneralEventHandler.onApplyLootingLevel(SpectriteGeneralEventHandler.java:749)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_SpectriteGeneralEventHandler_onApplyLootingLevel_LootingLevelEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:627)
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:619)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1180)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at weather2.entity.EntityMovingBlock.func_70071_h_(EntityMovingBlock.java:253)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: weather2:moving_block (weather2.entity.EntityMovingBlock)
	Entity ID: 138260
	Entity Name: entity.moving_block.name
	Entity's Exact location: 512.48, 99.93, 31.48
	Entity's Block location: World: (512,99,31), Chunk: (at 0,6,15 in 32,1; contains blocks 512,0,16 to 527,255,31), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.04, 1.57, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Weather2_Holz
	All players: 1 total; [EntityPlayerMP['dagobertdu94'/31, l='Weather2_Holz', x=529.39, y=69.88, z=41.08]]
	Chunk stats: ServerChunkCache: 470 Drop: 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: []
	Level spawn location: World: (602,4,-119), Chunk: (at 10,0,9 in 37,-8; contains blocks 592,0,-128 to 607,255,-113), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 13899 game time, 13899 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 41935 (now: false), thunder time: 106992 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 530521592 bytes (505 MB) / 1107296256 bytes (1056 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2638 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version       | Source                                | Signature                                |
	|:--------- |:---------------- |:------------- |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.2        | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp              | 9.42          | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99     | forge-1.12.2-14.23.2.2638.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.23.2.2638  | forge-1.12.2-14.23.2.2638.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | extendedrenderer | v1.0          | coroutil-1.12.1-1.2.31.jar            | None                                     |
	| UCHIJAAAA | coroutil         | 1.12.1-1.2.31 | coroutil-1.12.1-1.2.31.jar            | None                                     |
	| UCHIJAAAA | configmod        | v1.0          | coroutil-1.12.1-1.2.31.jar            | None                                     |
	| UCHIJAAAA | spectrite        | 1.6.1         | Spectrite-Mod-1.12.jar                | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCHIJAAAA | weather2         | 1.12.1-2.6.12 | weather2-1.12.1-2.6.12.jar            | None                                     |
	| UCHIJAAAA | worldedit        | 6.1.8         | worldedit-forge-mc1.12-6.1.8-dist.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['dagobertdu94'/31, l='Weather2_Holz', x=529.39, y=69.88, z=41.08]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

Ich wurde vom Weather2-Entwickler hierher umgeleitet, nachdem wir "gemeinsam" herausgefunden haben, dass der Fehler durch die Spectrite-Mod verursacht wird. Ich würde mich freuen, wenn dies behoben werden könnte, denn ich nutze die Mod schon gerne, aber momentan kann ich das leider nicht.
Lange Rede, kurzer Sinn: Es würde vermutlich auch andere Weather2- und Spectrite-Nutzer glücklich machen, denke ich...

Gruß **dagobertdu94**

**Comment by Flashfyre** [comment]
This has already been fixed, you are using an old version. Please update the mod.

**Comment by dagobertdu94** [comment]
Stimmt, jetzt weiß ich wieder, warum ich immer nur die alten Sachen hab und nie was neues...
Sorry, wenn ich deine Zeit verschwendet haben sollte.
